Added output details

diff --git a/sailboat/opt/custom/bin/start b/sailboat/opt/custom/bin/start
--- a/sailboat/opt/custom/bin/start
+++ b/sailboat/opt/custom/bin/start
@@ -78,17 +78,37 @@ Vk0gQm9vdGVyCgo=' | \
     done
     echo ""
 
+    vmadm list | grep -w "$UUID" 2>/dev/null >/dev/null
+      if [ $? == 0 ]; then
+        BRAND=$(vmadm get "$UUID" | json -a brand)
+        break
+          else echo "UUID not found. Please check spelling and try again"; fi
+
     while true; do
         vmadm start "$UUID"
         while true; do
-            vmadm list uuid="$UUID"
+          echo "[*] Awaiting network"
+          if [ "$BRAND" == joyent ]; then
             echo ""
-            echo "[*] Awaiting network"
-            if [ "$BRAND" == joyent ]; then zlogin "$UUID" ipadm show-addr; fi
-            if [ "$BRAND" == lx ]; then zlogin "$UUID" ip a; fi
-            if [ "$BRAND" == kvm ]; then vmadm info "$UUID" vnc; fi
+            echo "[*] ipadm show-addr"
+            zlogin "$UUID" ipadm show-addr
             echo ""
-            read -p "Press enter to refresh network lookup, or ^C to exit"
+            echo "[*] netstat -rn"
+            zlogin "$UUID" netstat -rn; fi
+          if [ "$BRAND" == lx ]; then
+            echo ""
+            echo "[*] /sbin/ip a"
+            zlogin "$UUID" /sbin/ip a
+            echo ""
+            echo "[*] /bin/netstat -rn"
+            zlogin "$UUID" /bin/netstat -rn; fi
+          if [ "$BRAND" == kvm ]; then
+            echo ""
+            echo "[*] VNC"
+            vmadm info "$UUID" vnc; fi
+          echo ""
+          read -p "Press enter to refresh network lookup, or type quit " ANSWER
+          if [ "$ANSWER" == quit ]; then break; fi
         done
     done
     echo ""
