Squishy bugs

diff --git a/sailboat/opt/custom/bin/vmadm-create-vm b/sailboat/opt/custom/bin/vmadm-create-vm
--- a/sailboat/opt/custom/bin/vmadm-create-vm
+++ b/sailboat/opt/custom/bin/vmadm-create-vm
@@ -1275,21 +1275,23 @@ function vmadm_create(){
 
 function info(){
 
-  vmadm list | grep -w "$INFO" 2>/dev/null >/dev/null
-  read -p "Enter new VM UUID: " INFO
   while true; do
-    if [ $? == 0 ]; then
-      vmadm start "$INFO"
-      while true; do
-        echo "[*] Awaiting network"
-        if [ "$BRAND" == joyent ]; then zlogin "$INFO" ipadm show-addr; fi
-        if [ "$BRAND" == lx ]; then zlogin "$INFO" ip a; fi
-        if [ "$BRAND" == kvm ]; then vmadm info "$INFO" vnc; fi
-        echo ""
-        read -p "Press enter to refresh network lookup, or ^C to exit"
-      done
+    read -p "Enter new VM UUID: " INFO
+    vmadm list | grep -w "$INFO" 2>/dev/null >/dev/null
+      if [ $? == 0 ]; then break
+        else echo "UUID not found. Please check spelling and try again"; fi
+  done
 
-      else echo "UUID not found. Please check spelling and try again"; fi
+  while true; do
+    vmadm start "$INFO"
+    while true; do
+      echo "[*] Awaiting network"
+      if [ "$BRAND" == joyent ]; then zlogin "$INFO" ipadm show-addr; fi
+      if [ "$BRAND" == lx ]; then zlogin "$INFO" ip a; fi
+      if [ "$BRAND" == kvm ]; then vmadm info "$INFO" vnc; fi
+      echo ""
+      read -p "Press enter to refresh network lookup, or ^C to exit"
+    done
   done
   echo ""
   return $?
