Updated spec_oslx_image()

diff --git a/sailboat/opt/custom/bin/vmadm-create-vm b/sailboat/opt/custom/bin/vmadm-create-vm
--- a/sailboat/opt/custom/bin/vmadm-create-vm
+++ b/sailboat/opt/custom/bin/vmadm-create-vm
@@ -318,20 +318,22 @@ function spec_oslx_image(){
   #    Normally you do *not* want to set this for KVM.
 
 
-  echo ""
-  imgadm list -o uuid,name,version,os,type,published | head -1
-  imgadm list -o uuid,name,version,os,type,published | grep linux
-  echo ""
   while true; do
-    read -p "Select existing image: " IMAGE_UUID
-    if [ ! -z "$IMAGE_UUID" ]; then imgadm list | grep "$IMAGE_UUID" 2>/dev/null >/dev/null; fi
-    if [ $? == 0 ]; then break
-      else echo "Image UUID does not exist. Check your spelling and try again"; fi
-    sleep 2
+
     echo ""
-    imgadm list -o uuid,name,version,os,type,published | head -1
-    imgadm list -o uuid,name,version,os,type,published | grep linux
-    echo ""
+    if [ "$BRAND" == os ]; then
+      imgadm list -o uuid,name,version,os,type,published | grep -vw bsd | grep -vw other | grep -vw linux | grep -vw lx-dataset; fi
+
+    if [ "$BRAND" == lx ]; then
+      imgadm list -o uuid,name,version,os,type,published | grep -w lx-dataset; fi
+
+      echo ""
+      read -p "Select existing image: " IMAGE_UUID
+      if [ -z "$IMAGE_UUID" ]; then echo "Missing UUID"
+        else imgadm list | grep -w "$IMAGE_UUID" 2>/dev/null >/dev/null
+          if [ $? == 0 ]; then break
+            else echo "Image UUID does not exist. Check your spelling and try again"; sleep 2; fi
+      fi
   done
   cat >> $TEMP << EOF
   "image_uuid": "$IMAGE_IMPORT_UUID",
@@ -434,7 +436,7 @@ function spec_kvm_disk(){
   echo "Select disk type"
   select KVM_DISK_TYPE in "Blank: New empty disk" "Image: Disk from an image"; do
     case $KVM_DISK_TYPE in
-    "Blank: New empty disk") KVM_DISK_TYPE=blank; break;;
+    "Blank: New empty disk") KVM_DISK_TYPE="$default"; break;;
     "Image: Disk from an image") KVM_DISK_TYPE=image; break;;
     esac
   done
@@ -487,31 +489,29 @@ function spec_kvm_disk(){
   fi
 
   if [ "$KVM_DISK_TYPE" == image ]; then
-  echo ""
-  imgadm list -o uuid,name,version,os,type,published | head -1
-  imgadm list -o uuid,name,version,os,type,published | grep linux
-  echo ""
+
   while true; do
+    echo ""
+    imgadm list -o uuid,name,version,os,type,published | grep -vw other | grep -vw lx-dataset | grep -vw smartos
+    echo ""
     read -p "Select existing image: " IMAGE_UUID
-    if [ ! -z "$IMAGE_UUID" ]; then imgadm list | grep "$IMAGE_UUID" 2>/dev/null >/dev/null; fi
-    if [ $? == 0 ]; then break
-      else echo "Image UUID does not exist. Check your spelling and try again"; fi
-    sleep 2
-    echo ""
-    imgadm list -o uuid,name,version,os,type,published | head -1
-    imgadm list -o uuid,name,version,os,type,published | grep linux
-    echo ""
+    if [ -z "$IMAGE_UUID" ]; then echo "Missing UUID"
+      else imgadm list | grep -w "$IMAGE_UUID" 2>/dev/null >/dev/null
+        if [ $? == 0 ]; then break
+          else echo "Image UUID does not exist. Check your spelling and try again"; sleep 2; fi
+    fi
   done
+
   while true; do
+    echo ""
+    imgadm list -o uuid,name,version,os,type,published | grep -vw other | grep -vw lx-dataset | grep -vw smartos
+    echo ""
     read -p "Image name: " IMAGE_NAME
-    if [ ! -z "$IMAGE_NAME" ]; then imgadm list | grep "$IMAGE_NAME" 2>/dev/null >/dev/null; fi
-    if [ $? == 0 ]; then break
-      else echo "Image name does not exist. Check your spelling and try again"; fi
-    sleep 2
-    echo ""
-    imgadm list -o uuid,name,version,os,type,published | head -1
-    imgadm list -o uuid,name,version,os,type,published | grep linux
-    echo ""
+    if [ -z "$IMAGE_NAME" ]; then echo "Missing image name"
+      else imgadm list | grep -w "$IMAGE_NAME" 2>/dev/null >/dev/null
+        if [ $? == 0 ]; then break
+          else echo "Image name does not exist. Check your spelling and try again"; sleep 2; fi
+    fi
   done
 
   echo "Select max disk allocation (in MB)"
@@ -619,15 +619,15 @@ function spec_nics(){
     if [ -z "$INTERFACE" ]; then INTERFACE=$INTERFACE_default; fi
 
     echo "Select NIC type to use"
-    select ANSWER in "NIC Tag (default)" "virtual NIC" "etherstub"; do
+    select ANSWER in "NIC tag (default)" "virtual NIC" "etherstub"; do
       case $ANSWER in
-        "NIC Tag (default)")
+        "NIC tag (default)")
           while true; do
             nictagadm list | head -1; nictagadm list | grep normal
-            read -p "Set NIC Tag for traffic to go over (external): " NICTAG
+            read -p "Set NIC tag for traffic to go over (external): " NICTAG
             if [ -z "$NICTAG" ]; then NICTAG=$NICTAG_default; fi
-            if [ ! -z "$NICTAG" ]; then nictagadm list | grep "$NICTAG" 2>/dev/null >/dev/null
-              if [ ! $? == 0 ]; then echo "NIC Tag not found. Check spelling and try again"
+            if [ ! -z "$NICTAG" ]; then nictagadm list | grep -w "$NICTAG" 2>/dev/null >/dev/null
+              if [ ! $? == 0 ]; then echo "NIC tag not found. Check spelling and try again"
                 else break; fi
             fi
           done
@@ -637,8 +637,8 @@ function spec_nics(){
           while true; do
           dladm show-vnic
           read -p "Set virtual NIC: " NICTAG
-          if [ -z "$NICTAG" ]; then echo "You must enter in a virtual NIC"
-            else dladm show-vnic | grep "$NICTAG" 2>/dev/null >/dev/null
+          if [ -z "$NICTAG" ]; then echo "You must enter in a virtual NIC"; sleep 2
+            else dladm show-vnic | grep -w "$NICTAG" 2>/dev/null >/dev/null
               if [ ! "$?" == 0 ]; then echo "Virtual NIC not found. Check spelling and try again"
                 else break; fi
           fi
@@ -649,8 +649,8 @@ function spec_nics(){
           while true; do
           dladm show-etherstub
           read -p "Set etherstub: " NICTAG
-          if [ -z "$NICTAG" ]; then echo "You must enter an etherstub"
-            else dladm show-etherstub | grep "$NICTAG" 2>/dev/null >/dev/null
+          if [ -z "$NICTAG" ]; then echo "You must enter an etherstub"; sleep 2
+            else dladm show-etherstub | grep -w "$NICTAG" 2>/dev/null >/dev/null
               if [ ! "$?" == 0 ]; then echo "Etherstub not found. Check spelling and try again"
                 else break; fi
           fi
@@ -658,6 +658,8 @@ function spec_nics(){
           break ;;
       esac
     done
+    break
+  done
 
     echo "Set NIC as default gw?"
     select ANSWER in "Yes (default)" "No"; do
